- name: install and start nginx
  hosts: mongodb
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        status: installed
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        status: started