- name: create user
  hosts: localhost
  vars_prompt:
    - name: user
      prompt: What is your username?
      private: false
  tasks:
    - name: user exists check and create user
      ansible.builtin.command: id {{user}}
      register: output
      ignore_errors: true
        ansible.builtin.user:
          name: roboshop
        when: user_cvar.rc != 0

