- name: variables
  hosts: localhost
  vars:
    COURSE: Devops
    TRAINER: Sivakumar
    DURATION: 110
  tasks:
    - name: print with play variables
      ansible.builtin.debug:
        msg: "Trainer is {{TRAINER}} and {{COURSE}} duration is {{DURATION}}"
    - name: print task varibales
      vars:
        COURSE: Testing
        TRAINER: Naresh
        DURATION: 10
      ansible.builtin.debug:
        msg: "Trainer is {{TRAINER}} and {{COURSE}} duration is {{DURATION}}"
    